language: java
jdk:
  - openjdk8

# Travis CI를 어느 브랜치가 푸시될 때 수행할지 지정한다.
# 현재는 master 브랜치에 push 될 때만 수행한다.
branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때무터 다시
# 받지 않도록 설정한다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시되었을 때 수행하는 명령어이다.
script: "./gradlew clean build"

before_deploy:
  # CodeDeploy는 Jar 파일은 인식하지 못하므로 Jar+기타 설정 파일들을 모아 압축
  - zip -r board-springboot2 *
  # 현재 위치의 모든 파일을 board-springboot2 이름으로 압축한다.
  - mkdir -p deploy
  - mv board-springboot2.zip deploy/board-springboot2.zip

deploy:
  # S3로 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위들을 선언한다.
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: board-springboot2-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    # 앞에서 생성한 deploy 디렉토리를 지정한다.
    # 해당 ㅜ이치의 파일들만 S3로 전송한다.
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - gkswjddyd4@gmail.com