# Travis CI의 Build가 끝나면 S3에 zip 파일이 전송되고, 이 zip 파일은
# /home/ec2-user/app/step2/zip 으로 복사되어 압축을 풀 예정이다.
# Travis CI의 설정은 .travis.yml
# AWS CodeDeploy의 설정은 appspec.yml

version: 0.0
# CodeDeploy 버전
# 프로젝트 버전이 아니므로 0.0 외에 다른 버전을 사용하면 오류가 발생한다.

os: linux
files:
  - source: /
    # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 지정한다.
    # 루트 경로(/)를 지정하면 전체 파일을 이야기한다.
    destination: /home/ec2-user/app/step2/zip/
    # source에서 지정된 파일을 받을 위치다.
    # 이후 Jar를 실행하는 등은 destination에서 옮긴 파일들로 진행된다.
    overwrite: yes
    # 기존에 파일들이 있으면 덮어쓸지 결정한다.
    # yes라고 했으니 파일들을 덮어쓴다.

permissions:
  # CodeDeploy 에서 Ec2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 한다.
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  # CodeDeploy 배포 단계에서 실행할 명령어를 지정한다.
  # ApplicationStart 라는 단계에서 deploy.sh를 ec2-user 권한으로 실행하게 한다.
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      # 스크립트 실행 시 60초 이상 수행되면 실패가 된다.
      runas: ec2-user